import smerdova from '../../static/images/people/smerdova.jpg'
import drevojan from '../../static/images/people/drevojan.jpg'
import lososova from '../../static/images/people/lososova.jpg'
import bonari from '../../static/images/people/bonari.jpg'
import divisek from '../../static/images/people/divisek.jpg'
import jaskova from '../../static/images/people/jaskova.jpg'
import novak from '../../static/images/people/novak.jpg'


export const peopleEn = [
  {
    id: `chytry`,
    name: `Milan Chytrı`,
    position: `Group Head`,
    description: ``,
    email: `chytry@sci.muni.cz`,
    phoneNumber: `549494595`,
    researchgate: `https://www.researchgate.net/profile/Milan_Chytry`,
    is: `http://www.sci.muni.cz/botany/chytry/`,
  },
  {
    id: `danihelka`,
    name: `Jiøí Danihelka`,
    position: `Researcher`,
    description: ``,
    email: `danihel@sci.muni.cz`,
    phoneNumber: `549493473`,
    researchgate: `https://www.researchgate.net/profile/Jii_Danihelka`,
    is: `https://www.muni.cz/en/people/5926-jiri-danihelka`,
  },
  {
    id: `divisek`,
    name: `Jan Divíšek`,
    position: `Researcher`,
    description: ``,
    email: `divisekjan@mail.muni.cz`,
    phoneNumber: `549498494`,
    researchgate: `https://www.researchgate.net/profile/Jan_Divisek`,
    is: `https://www.muni.cz/en/people/106310-jan-divisek`,
	img: divisek
  }, 
  {
    id: `lososova`,
    name: `Zdeòka Lososová`,
    position: `Researcher`,
    description: `Zdeòka Lososová has been employed at the Department of Botany and Zoology of the Masaryk University since 2004. She is a guarantee of study programmes of Secondary school teacher training in biology. She leads the botanical and geobotanical seminars, she also participates on leading field course of Methods of geobotany. Her current scientific interests focus on diversity of vegetation, her main interest goes mainly to the vegetation of human made habitats. One of the main study areas is effect of urban environment on occurrences of vascular plants in European cities. Closely related study topics are those of biological invasions. Recently she focusses on the research of phylogenetic and functional diversity of plant communities. Based on these characteristics of plant communities she try to explain the role of environmental filtering and biotic interactions on the community assembly.`,
    email: `lososova@sci.muni.cz`,
    phoneNumber: `549498399`,
    researchgate: `https://www.researchgate.net/profile/Zdeka_Lososova`,
    is: `https://www.muni.cz/en/people/5767-zdenka-lososova`,
	img: lososova
  },
  {
    id: `rolecek`,
    name: `Jan Roleèek`,
    position: `Researcher`,
    description: ``,
    email: `honza.rolecek@centrum.cz`,
    phoneNumber: `549498489`,
    researchgate: `https://www.researchgate.net/scientific-contributions/78391540_Jan_Rolecek`,
    is: `https://www.muni.cz/en/people/42706-jan-rolecek`,
  },
  {
    id: `tesitel`,
    name: `Jakub Tìšitel`,
    position: `Researcher`,
    description: ``,
    email: `tesitel@sci.muni.cz`,
    phoneNumber: `549496974`,
    researchgate: `https://www.researchgate.net/scientific-contributions/46226749_Jakub_Tesitel`,
    is: `https://www.muni.cz/en/people/116967-jakub-tesitel`,
  },
  {
    id: `tichy`,
    name: `Lubomír Tichı`,
    position: `Researcher`,
    description: ``,
    email: `tichy@sci.muni.cz`,
    phoneNumber: `549497673`,
    researchgate: `https://www.researchgate.net/scientific-contributions/14637372_Lubomir_Tichy`,
    is: `https://www.muni.cz/en/people/6669-lubomir-tichy`,
  },
  {
    id: `axmanova`,
    name: `Irena Axmanová`,
    position: `Researcher`,
    description: ``,
    email: `axmanova@sci.muni.cz`,
    phoneNumber: `549498395`,
    researchgate: `https://www.researchgate.net/profile/Irena_Axmanova`,
    is: `https://www.muni.cz/en/people/78388-irena-axmanova`,
  },
  {
    id: `bonari`,
    name: `Gianmaria Bonari`,
    position: `Researcher`,
    description: `Gianmaria Bonari received his B.Sc., M.Sc. and Ph.D. at the University of Siena (Italy). Currently, he is a postdoctoral researcher at the Masaryk University of Brno (Czech Republic). His scientific interests fill the niches of Botany and Vegetation Science. His research involves a thorough understanding of European (but also North African and Near East ones) pine forests, with a particular focus on the Mediterranean and Submediterranean types. His academic training includes ecoinformatics, classification of plant communities and habitats, management and conservation aspects, also favouring an integrated view which fosters crosswalks between plant and animal communities. He is the custodian of the CircumMed vegetation-plot database which was developed for broad-scale studies on vegetation classification, plant invasion ecology, macroecology and biological conservation. Being a vegetation ecologist, he is aware that the understanding of the complexity of communities also passes by field research. This makes him an active field botanist.`,
    email: `gianmaria.bonari@gmail.com`,
    phoneNumber: `549498479`,
    researchgate: `https://www.researchgate.net/profile/Gianmaria_Bonari2`,
    is: `https://www.muni.cz/en/people/403975-gianmaria-bonari`,
    img: bonari
  },
  {
    id: `cubino`,
    name: `Josep Padulles Cubino`,
    position: `Researcher`,
    description: ``,
    email: `padulles@sci.muni.cz`,
    phoneNumber: `549498477`,
    researchgate: `https://www.researchgate.net/profile/Josep_Padulles`,
    is: `https://www.muni.cz/en/people/243613-josep-padulles-cubino`,
  },
  {
    id: `ceplova`,
    name: `Natálie Èeplová`,
    position: `Researcher`,
    description: ``,
    email: `ceplova@ped.muni.cz`,
    phoneNumber: `549494992`,
    researchgate: `https://www.researchgate.net/profile/Natalie_Ceplova`,
    is: `https://www.muni.cz/en/people/13913-natalie-ceplova`,
  },
  {
    id: `fischer`,
    name: `Felícia Miranda Fischer`,
    position: `Researcher`,
    description: ``,
    email: `feliciafischerster@gmail.com`,
    phoneNumber: `549498479`,
    researchgate: `https://www.researchgate.net/profile/Felicia_Fischer`,
    is: `https://www.muni.cz/en/people/243002-felicia-miranda-fischer`,
  },
  {
    id: `gotzenberger`,
    name: `Lars Götzenberger`,
    position: `Researcher`,
    description: ``,
    email: `lars.goetzenberger@gmail.com`,
    phoneNumber: ``,
    researchgate: `https://www.researchgate.net/profile/Lars_Goetzenberger`,
    is: `https://www.muni.cz/en/people/238736-lars-goetzenberger`,
  },
  {
    id: `hajek`,
    name: `Ondøej Hájek`,
    position: `Researcher`,
    description: ``,
    email: `ohajek@sci.muni.cz`,
    phoneNumber: `549494033`,
    researchgate: `https://www.researchgate.net/profile/Ondej_Hajek`,
    is: `https://www.muni.cz/en/people/16845-ondrej-hajek`,
  },
  {
    id: `holubova`,
    name: `Dana Holubová`,
    position: `Researcher`,
    description: ``,
    email: `danmich@mail.muni.cz`,
    phoneNumber: `549496974`,
    researchgate: `https://www.researchgate.net/scientific-contributions/2149640262_Dana_Holubova`,
    is: `https://www.muni.cz/en/people/113226-dana-holubova`,
  },
  {
    id: `kalusova`,
    name: `Veronika Kalusová`,
    position: `Researcher`,
    description: ``,
    email: `kalveron@tiscali.cz`,
    phoneNumber: `549494992`,
    researchgate: `https://www.researchgate.net/profile/Veronika_Kalusova`,
    is: `https://www.muni.cz/en/people/106856-veronika-kalusova`,
  },
  {
    id: `knollova`,
    name: `Ilona Knollová`,
    position: `Researcher`,
    description: ``,
    email: `ikuzel@sci.muni.cz`,
    phoneNumber: `549498488`,
    researchgate: `https://www.researchgate.net/profile/Ilona_Knollova`,
    is: `https://www.muni.cz/en/people/10355-ilona-knollova`,
  },
  {
    id: `kubesova`,
    name: `Svatava Kubešová`,
    position: `Researcher`,
    description: ``,
    email: `skubesova@mzm.cz`,
    phoneNumber: `545217322`,
    researchgate: `https://www.researchgate.net/profile/Svatava_Kubesova`,
    is: `https://www.muni.cz/en/people/18604-svatava-kubesova`,
  },
  {
    id: `landucci`,
    name: `Flavia Landucci`,
    position: `Researcher (maternity leave)`,
    description: ``,
    email: `386683@mail.muni.cz`,
    phoneNumber: `549498479`,
    researchgate: `https://www.researchgate.net/profile/Flavia_Landucci`,
    is: `https://www.muni.cz/en/people/386683-flavia-landucci`,
  },
   {
    id: `preislerova`,
    name: `Zdenka Preislerová`,
    position: `Researcher`,
    description: ``,
    email: `zpreislerova@gmail.com`,
    phoneNumber: `549498477`,
    researchgate: `https://www.researchgate.net/profile/Zdenka_Preislerova`,
    is: `https://www.muni.cz/en/people/10230-zdenka-preislerova`,
  },
   {
    id: `reznickova`,
    name: `Marcela Øezníèková`,
    position: `Researcher`,
    description: ``,
    email: `mar.reznickova@seznam.cz`,
    phoneNumber: `549498488`,
    researchgate: `https://www.researchgate.net/profile/Marcela_Reznickova`,
    is: `https://www.muni.cz/en/people/19437-marcela-reznickova`,
  },
  {
    id: `smerdova`,
    name: `Eva Šmerdová (Hettenbergerová)`,
    position: `Researcher`,
    description: `Eva Šmerdová studied Plant Systematics and Ecology at University of Ostrava. She continued in master study of botany at Masaryk University, Brno and was graduated in 2006. Her master thesis dealt with the effect of contact plant communities on the species composition of spring fens. Her PhD thesis dealt with species richness of plants and molluscs along the moisture gradient. Currently she works on database of plant macrofossils of Czech and Slovak Republic. She likes to travel with co-workers to sample field data for the next research`,
    email: `eva.hette@centrum.cz`,
    phoneNumber: `549498487`,
    researchgate: `https://www.researchgate.net/scientific-contributions/85483229_Eva_Hettenbergerova`,
    is: `https://www.muni.cz/en/people/75764-eva-smerdova`,
    img: smerdova
  },
   {
    id: `stepankova`,
    name: `Petra Štìpánková`,
    position: `Researcher`,
    description: ``,
    email: `pstepankova@sci.muni.cz`,
    phoneNumber: `549498389`,
    is: `https://www.muni.cz/en/people/234942-petra-stepankova`,
  },
   {
    id: `taborska`,
    name: `Markéta Táborská`,
    position: `Researcher (maternity leave)`,
    description: ``,
    email: `taborska.mar@gmail.com`,
    phoneNumber: `549498474`,
    researchgate: `https://www.researchgate.net/profile/Marketa_Taborska`,
    is: `https://www.muni.cz/en/people/222793-marketa-taborska`,
  },
   {
    id: `drevojan`,
    name: `Pavel Døevojan`,
    position: `Researcher`,
    description: ``,
    email: `269768@mail.muni.cz`,
    phoneNumber: `549498486`,
    researchgate: `https://www.researchgate.net/profile/Pavel_Devojan`,
    is: `https://www.muni.cz/en/people/269768-pavel-drevojan`,
    img: drevojan
  },
   {
    id: `galuskova`,
    name: `Hana Galušková`,
    position: `Researcher`,
    description: ``,
    email: `357936@mail.muni.cz`,
    phoneNumber: `549494813`,
    is: `https://www.muni.cz/en/people/357936-hana-galuskova`,
  },
   {
    id: `chudomelova`,
    name: `Markéta Chudomelová`,
    position: `Researcher`,
    description: ``,
    email: `323585@mail.muni.cz`,
    phoneNumber: `541126221`,
    researchgate: `https://www.researchgate.net/profile/Marketa_Chudomelova`,
    is: `https://www.muni.cz/en/people/323585-marketa-chudomelova`,
  }, 
   {
    id: `jaskova`,
    name: `Anni Kanerva Jašková (Pyykönen)`,
    position: `Researcher`,
    description: ``,
    email: `annipyy@mail.muni.cz`,
    phoneNumber: `549498395`,
    researchgate: `https://www.researchgate.net/profile/Anni_Pyykoenen`,
    is: `https://www.muni.cz/en/people/452344-anni-kanerva-pyykoenen`,
	img: jaskova
  },
    {
    id: `kalnikova`,
    name: `Veronika Kalníková`,
    position: `Researcher`,
    description: ``,
    email: `V.Kalnikova@seznam.cz`,
    phoneNumber: `549498486`,
    researchgate: `https://www.researchgate.net/profile/Veronika_Kalnikova`,
    is: `https://www.muni.cz/en/people/222967-veronika-kalnikova`,
  },
   {
    id: `novak`,
    name: `Pavel Novák`,
    position: `Researcher`,
    description: ``,
    email: `269109@mail.muni.cz`,
    phoneNumber: `549498485`,
    researchgate: `https://www.researchgate.net/profile/Pavel_Novak21`,
    is: `https://www.muni.cz/en/people/269109-pavel-novak`,
	img: novak
  },

   {
    id: `spanikova`,
    name: `Šárka Špániková`,
    position: `Researcher`,
    description: ``,
    email: `408322@mail.muni.cz`,
    phoneNumber: ``,
    is: `https://www.muni.cz/en/people/408322-sarka-spanikova`,
  },
   {
    id: `vecera`,
    name: `Martin Veèeøa`,
    position: `Researcher`,
    description: ``,
    email: `martinvec@seznam.cz`,
    phoneNumber: `549498494`,
    researchgate: `https://www.researchgate.net/profile/Martin_Vecera`,
    is: `https://www.muni.cz/en/people/357693-martin-vecera`,
  },
   {
    id: `zukal`,
    name: `Dominik Zukal`,
    position: `Researcher`,
    description: ``,
    email: `375623@mail.muni.cz`,
    phoneNumber: `549498494`,
    researchgate: `https://www.researchgate.net/profile/Dominik_Zukal`,
    is: `https://www.muni.cz/en/people/375623-dominik-zukal`,
  },   
]

export const peopleCz = [
  {
    id: `chytry`,
    name: `Milan Chytrı`,
    position: `Vedoucí skupiny`,
    description: ``,
    email: `chytry@sci.muni.cz`,
	phoneNumber: `549494595`,
    researchgate: `https://www.researchgate.net/profile/Milan_Chytry`,
    is: `http://www.sci.muni.cz/botany/chytry/`,
  },
  {
    id: `danihelka`,
    name: `Jiøí Danihelka`,
    position: `Researcher`,
    description: ``,
    email: `danihel@sci.muni.cz`,
    phoneNumber: `549493473`,
    researchgate: `https://www.researchgate.net/profile/Jii_Danihelka`,
    is: `https://www.muni.cz/lide/5926-jiri-danihelka`,
  },
  {
    id: `divisek`,
    name: `Jan Divíšek`,
    position: `Researcher`,
    description: ``,
    email: `divisekjan@mail.muni.cz`,
    phoneNumber: `549498494`,
    researchgate: `https://www.researchgate.net/profile/Jan_Divisek`,
    is: `https://www.muni.cz/lide/106310-jan-divisek`,
	img: divisek
  }, 
  {
    id: `lososova`,
    name: `Zdeòka Lososová`,
    position: `Docent`,
    description: `Zdeòka Lososová pracuje na Ústavu botaniky a zoologie od roku 2004. Je garantkou bakaláøského a navazujícího magisterského studia uèitelství biologie pro støední školy. Podílí se na vıuce botanickıch a geobotanickıch semináøù a terénního cvièení z geobotaniky. Ve vızkumu se zabıvá diverzitou vegetace, soustøedí se pøedevším (ale nejenom) na vegetaci antropogenních stanoviš. Jedním z hlavních vızkumnıch témat je  vliv prostøedí velkıch evropskıch mìst na vıskyt cévnatıch rostlin. S tímto tématem souvisí otázky invazní biologie. V posledních letech se soustøedí na studium funkèní a fylogenetické diverzity rostlinnıch spoleèenstev. Pomocí tìchto charakteristik rostlinnıch spoleèenstev se snaí pochopit, do jaké míry utváøejí rostlinná spoleèenstva podmínky prostøedí a do jaké míry to jsou biotické interakce.`,
    email: `lososova@sci.muni.cz`,
	phoneNumber: `549498399`,
    researchgate: `https://www.researchgate.net/profile/Zdeka_Lososova`,
    is: `https://www.muni.cz/lide/5767-zdenka-lososova`,
	img: lososova
  },
  {
    id: `rolecek`,
    name: `Jan Roleèek`,
    position: `Researcher`,
    description: ``,
    email: `honza.rolecek@centrum.cz`,
    phoneNumber: `549498489`,
    researchgate: `https://www.researchgate.net/scientific-contributions/78391540_Jan_Rolecek`,
    is: `https://www.muni.cz/lide/42706-jan-rolecek`,
  },
  {
    id: `tesitel`,
    name: `Jakub Tìšitel`,
    position: `Researcher`,
    description: ``,
    email: `tesitel@sci.muni.cz`,
    phoneNumber: `549496974`,
    researchgate: `https://www.researchgate.net/scientific-contributions/46226749_Jakub_Tesitel`,
    is: `https://www.muni.cz/lide/116967-jakub-tesitel`,
  },
  {
    id: `tichy`,
    name: `Lubomír Tichı`,
    position: `Researcher`,
    description: ``,
    email: `tichy@sci.muni.cz`,
    phoneNumber: `549497673`,
    researchgate: `https://www.researchgate.net/scientific-contributions/14637372_Lubomir_Tichy`,
    is: `https://www.muni.cz/lide/6669-lubomir-tichy`,
  },
  {
    id: `axmanova`,
    name: `Irena Axmanová`,
    position: `Researcher`,
    description: ``,
    email: `axmanova@sci.muni.cz`,
    phoneNumber: `549498395`,
    researchgate: `https://www.researchgate.net/profile/Irena_Axmanova`,
    is: `https://www.muni.cz/lide/78388-irena-axmanova`,
  },
  {
    id: `bonari`,
    name: `Gianmaria Bonari`,
    position: `Researcher`,
    description: `Gianmaria Bonari received his B.Sc., M.Sc. and Ph.D. at the University of Siena (Italy). Currently, he is a postdoctoral researcher at the Masaryk University of Brno (Czech Republic). His scientific interests fill the niches of Botany and Vegetation Science. His research involves a thorough understanding of European (but also North African and Near East ones) pine forests, with a particular focus on the Mediterranean and Submediterranean types. His academic training includes ecoinformatics, classification of plant communities and habitats, management and conservation aspects, also favouring an integrated view which fosters crosswalks between plant and animal communities. He is the custodian of the CircumMed vegetation-plot database which was developed for broad-scale studies on vegetation classification, plant invasion ecology, macroecology and biological conservation. Being a vegetation ecologist, he is aware that the understanding of the complexity of communities also passes by field research. This makes him an active field botanist.`,
    email: `gianmaria.bonari@gmail.com`,
    phoneNumber: `549498479`,
    researchgate: `https://www.researchgate.net/profile/Gianmaria_Bonari2`,
    is: `https://www.muni.cz/lide/403975-gianmaria-bonari`,
    img: bonari
  },
  {
    id: `cubino`,
    name: `Josep Padulles Cubino`,
    position: `Researcher`,
    description: ``,
    email: `padulles@sci.muni.cz`,
    phoneNumber: `549498477`,
    researchgate: `https://www.researchgate.net/profile/Josep_Padulles`,
    is: `https://www.muni.cz/lide/243613-josep-padulles-cubino`,
  },
  {
    id: `ceplova`,
    name: `Natálie Èeplová`,
    position: `Researcher`,
    description: ``,
    email: `ceplova@ped.muni.cz`,
    phoneNumber: `549494992`,
    researchgate: `https://www.researchgate.net/profile/Natalie_Ceplova`,
    is: `https://www.muni.cz/lide/13913-natalie-ceplova`,
  },
  {
    id: `fischer`,
    name: `Felícia Miranda Fischer`,
    position: `Researcher`,
    description: ``,
    email: `feliciafischerster@gmail.com`,
    phoneNumber: `549498479`,
    researchgate: `https://www.researchgate.net/profile/Felicia_Fischer`,
    is: `https://www.muni.cz/lide/243002-felicia-miranda-fischer`,
  },
  {
    id: `gotzenberger`,
    name: `Lars Götzenberger`,
    position: `Researcher`,
    description: ``,
    email: `lars.goetzenberger@gmail.com`,
    phoneNumber: ``,
    researchgate: `https://www.researchgate.net/profile/Lars_Goetzenberger`,
    is: `https://www.muni.cz/lide/238736-lars-goetzenberger`,
  },
  {
    id: `hajek`,
    name: `Ondøej Hájek`,
    position: `Researcher`,
    description: ``,
    email: `ohajek@sci.muni.cz`,
    phoneNumber: `549494033`,
    researchgate: `https://www.researchgate.net/profile/Ondej_Hajek`,
    is: `https://www.muni.cz/lide/16845-ondrej-hajek`,
  },
  {
    id: `holubova`,
    name: `Dana Holubová`,
    position: `Researcher`,
    description: ``,
    email: `danmich@mail.muni.cz`,
    phoneNumber: `549496974`,
    researchgate: `https://www.researchgate.net/scientific-contributions/2149640262_Dana_Holubova`,
    is: `https://www.muni.cz/lide/113226-dana-holubova`,
  },
  {
    id: `kalusova`,
    name: `Veronika Kalusová`,
    position: `Researcher`,
    description: ``,
    email: `kalveron@tiscali.cz`,
    phoneNumber: `549494992`,
    researchgate: `https://www.researchgate.net/profile/Veronika_Kalusova`,
    is: `https://www.muni.cz/lide/106856-veronika-kalusova`,
  },
  {
    id: `knollova`,
    name: `Ilona Knollová`,
    position: `Researcher`,
    description: ``,
    email: `ikuzel@sci.muni.cz`,
    phoneNumber: `549498488`,
    researchgate: `https://www.researchgate.net/profile/Ilona_Knollova`,
    is: `https://www.muni.cz/lide/10355-ilona-knollova`,
  },
  {
    id: `kubesova`,
    name: `Svatava Kubešová`,
    position: `Researcher`,
    description: ``,
    email: `skubesova@mzm.cz`,
    phoneNumber: `545217322`,
    researchgate: `https://www.researchgate.net/profile/Svatava_Kubesova`,
    is: `https://www.muni.cz/lide/18604-svatava-kubesova`,
  },
  {
    id: `landucci`,
    name: `Flavia Landucci`,
    position: `Researcher (maternity leave)`,
    description: ``,
    email: `386683@mail.muni.cz`,
    phoneNumber: `549498479`,
    researchgate: `https://www.researchgate.net/profile/Flavia_Landucci`,
    is: `https://www.muni.cz/lide/386683-flavia-landucci`,
  },
   {
    id: `preislerova`,
    name: `Zdenka Preislerová`,
    position: `Researcher`,
    description: ``,
    email: `zpreislerova@gmail.com`,
    phoneNumber: `549498477`,
    researchgate: `https://www.researchgate.net/profile/Zdenka_Preislerova`,
    is: `https://www.muni.cz/lide/10230-zdenka-preislerova`,
  },
   {
    id: `reznickova`,
    name: `Marcela Øezníèková`,
    position: `Researcher`,
    description: ``,
    email: `mar.reznickova@seznam.cz`,
    phoneNumber: `549498488`,
    researchgate: `https://www.researchgate.net/profile/Marcela_Reznickova`,
    is: `https://www.muni.cz/lide/19437-marcela-reznickova`,
  },
 {
    id: `smerdova`,
    name: `Eva Šmerdová (Hettenbergerová)`,
    position: `Odbornı pracovník`,
    description: `Eva Šmerdová získala bakaláøskı titul na Ostravské Univerzitì, její práce se zamìøovala na flóru a vegetaci hald. Magisterské studium botaniky ukonèila v roce 2006 na PøF Masarykovy Univerzity v Brnì diplomovou prací zabıvající se vlivem kontaktních spoleèenstev na druhové sloení luèních prameniš. Doktorskou práci na téma druhová bohatost a variabilita rostlin a mìkkıšù na vlhkostním gradientu obhájila v roce 2013. V souèasné dobì se mimo jiné zabıvá tvorbou databáze rostlinnıch makrozbytkù Èeské a Slovenské republiky a doplòováním vegetaèních snímkù a jinıch údajù pro projekt PLADIAS. Ráda cestuje s kolegy po rodné vlasti i do zahranièí a sbírá terénní data k dalšímu vızkumu ekologie mokøadù i jinıch biotopù.`,
    email: `eva.hette@centrum.cz`,
    phoneNumber: `549498487`,
    researchgate: `https://www.researchgate.net/scientific-contributions/85483229_Eva_Hettenbergerova`,
    is: `https://www.muni.cz/lide/75764-eva-smerdova`,
    img: smerdova
  },
   {
    id: `stepankova`,
    name: `Petra Štìpánková`,
    position: `Researcher`,
    description: ``,
    email: `pstepankova@sci.muni.cz`,
    phoneNumber: `549498389`,
    is: `https://www.muni.cz/lide/234942-petra-stepankova`,
  },
   {
    id: `taborska`,
    name: `Markéta Táborská`,
    position: `Researcher (maternity leave)`,
    description: ``,
    email: `taborska.mar@gmail.com`,
    phoneNumber: `549498474`,
    researchgate: `https://www.researchgate.net/profile/Marketa_Taborska`,
    is: `https://www.muni.cz/lide/222793-marketa-taborska`,
  },
   {
    id: `drevojan`,
    name: `Pavel Døevojan`,
    position: `Odbornı pracovník`,
    description: `Pavel Døevojan vystudoval obor Botanika, smìr Ekologie rostlin na Pøírodovìdecké fakultì Masarykovy univerzity v Brnì. Ve své bakaláøské práci se vìnoval xerotermní flóøe a vegetaci záøezù eleznièní trati Veselí nad Moravou – Vrbovce a v rámci diplomové práce studoval diverzitu vegetace polních plevelù jihovıchodního Znojemska. Mezi jeho hlavní zájmy patøí studium flóry a vegetace jiní Moravy.`,
    email: `269768@mail.muni.cz`,
    phoneNumber: `549498486`,
    researchgate: `https://www.researchgate.net/profile/Pavel_Devojan`,
    is: `https://www.muni.cz/lide/269768-pavel-drevojan`,
    img: drevojan
  },
   {
    id: `galuskova`,
    name: `Hana Galušková`,
    position: `Researcher`,
    description: ``,
    email: `357936@mail.muni.cz`,
    phoneNumber: `549494813`,
    is: `https://www.muni.cz/lide/357936-hana-galuskova`,
  },
   {
    id: `chudomelova`,
    name: `Markéta Chudomelová`,
    position: `Researcher`,
    description: ``,
    email: `323585@mail.muni.cz`,
    phoneNumber: `541126221`,
    researchgate: `https://www.researchgate.net/profile/Marketa_Chudomelova`,
    is: `https://www.muni.cz/lide/323585-marketa-chudomelova`,
  }, 
    {
    id: `jaskova`,
    name: `Anni Kanerva Jašková (Pyykönen)`,
    position: `Researcher`,
    description: ``,
    email: `annipyy@mail.muni.cz`,
    phoneNumber: `549498395`,
    researchgate: `https://www.researchgate.net/profile/Anni_Pyykoenen`,
    is: `https://www.muni.cz/lide/452344-anni-kanerva-pyykoenen`,
	img: jaskova
  },
    {
    id: `kalnikova`,
    name: `Veronika Kalníková`,
    position: `Researcher`,
    description: ``,
    email: `V.Kalnikova@seznam.cz`,
    phoneNumber: `549498486`,
    researchgate: `https://www.researchgate.net/profile/Veronika_Kalnikova`,
    is: `https://www.muni.cz/lide/222967-veronika-kalnikova`,
  },
   {
    id: `novak`,
    name: `Pavel Novák`,
    position: `Researcher`,
    description: ``,
    email: `269109@mail.muni.cz`,
    phoneNumber: `549498485`,
    researchgate: `https://www.researchgate.net/profile/Pavel_Novak21`,
    is: `https://www.muni.cz/lide/269109-pavel-novak`,
	img: novak
  },

   {
    id: `spanikova`,
    name: `Šárka Špániková`,
    position: `Researcher`,
    description: ``,
    email: `408322@mail.muni.cz`,
    phoneNumber: ``,
    is: `https://www.muni.cz/lide/408322-sarka-spanikova`,
  },
   {
    id: `vecera`,
    name: `Martin Veèeøa`,
    position: `Researcher`,
    description: ``,
    email: `martinvec@seznam.cz`,
    phoneNumber: `549498494`,
    researchgate: `https://www.researchgate.net/profile/Martin_Vecera`,
    is: `https://www.muni.cz/lide/357693-martin-vecera`,
  },
   {
    id: `zukal`,
    name: `Dominik Zukal`,
    position: `Researcher`,
    description: ``,
    email: `375623@mail.muni.cz`,
    phoneNumber: `549498494`,
    researchgate: `https://www.researchgate.net/profile/Dominik_Zukal`,
    is: `https://www.muni.cz/lide/375623-dominik-zukal`,
  }, 
]